name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Reqs
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install -y -qq libegl1-mesa libegl1-mesa-dev libsdl2-dev libsdl2-image-dev

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Configure Conan ENV 
      run: export CONAN_USER_HOME="/tmp/conan" && export CONAN_SYSREQUIRES_MODE="enabled" && export CONAN_SYSREQUIRES_SUDO="1" 

    - name: Configure Conan Profile
      run: conan profile new default --detect && conan profile update settings.compiler.libcxx=libstdc++11 default && conan profile update conf.tools.system.package_manager:mode=install default && conan profile update conf.tools.system.package_manager:sudo=True default 

    - name: More Conan Config
      run: conan remove --system-reqs "*"
    
    - name: Configure Conan Install
      run: mkdir -p ${{github.workspace}}/build && conan install . -if ${{github.workspace}}/build/ --build missing

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cat CMakeLists.txt && cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --test-dir test/ -C ${{env.BUILD_TYPE}}
